sudo: false
language: ruby
matrix:
  include:
    - rvm: 2.1
      gemfile: bundler1.gemfile
    - rvm: 2.2
      gemfile: bundler1.gemfile
    - rvm: 2.3
    - rvm: 2.4
    - rvm: 2.5
    - rvm: 2.6
    - rvm: 2.7
    - rvm: ruby-head
